### ISSUE TITLE
Add usernames to D-Mail API

### ISSUE THREAD

**Issue by clragon** [zwagoth/e621ng#662] opened 2024-07-03 21:02 UTC
**Is your feature request related to a problem? Please describe.**
The D-Mail API only sends user IDs. 
This makes it hard to display the corresponding usernames.

**Describe the solution you'd like**
Adding username fields for both from and to to the API response.

**Describe alternatives you've considered**
I could request each user separately. This would terribly hurt everyone, the client and the server.

**Comment by Sindrake** [comment] 2024-07-24 16:25
This runs into the same issue as the rest of the "add usernames to X API endpoint" requests like #656.
Internally, the site _also_ requests usernames from the database one at a time. Which is terrible, and needs to be addressed.

https://github.com/e621ng/e621ng/blob/d0748f00bb055520f99609e1dfa89e4af1186758/app/models/user.rb#L160-L170

**Comment by Sindrake** [comment] 2024-08-03 09:17
This is effectively a duplicate of #656, as it requires the same fix.

**Closed as completed by Sindrake** 2024-08-03 09:17 UTC
Labels: Type: Duplicate, Type: Feature, API, DMails
